### PR TITLE
Convert Config API to Stable endpoints.

### PR DESCRIPTION
**Pull request by mukundansundar**
# Description

Convert Config API to Stable endpoints and client interface.

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation

### CODE REVIEW

**Review by pravinpushkar — DISMISSED** [review]
LGTM

**Comment by mukundansundar** [comment]
@dapr/maintainers-java-sdk For the error with Actors IT, I have created a separate issue in dapr runtime. 
https://github.com/dapr/dapr/issues/6268
The example validations with the new APIs pass as expected.

**Comment by mukundansundar** [comment]
@artursouza qq Should this PR be blocked on failures unrelated to config API? I am seeing actors, secrets and service invocation failing with the edge(probably a few days ago) version of dapr

**Comment by mukundansundar** [comment]
> We need to fix upstream. It is concerning to merge a PR that breaks the integration testing. 

I do agree on the part of merging something that breaks Java IT. 
Then this PR will remain open till changes are done in runtime to fix any issues.

**Review by artursouza — APPROVED** [review]

**Pull request merged**
