### PR TITLE
Add support for configuring actor reminder storage partitions

### PR DESCRIPTION
**Pull request by berndverst**
# Description

Add support for configuring actor reminder storage partitions

## Issue reference

https://github.com/dapr/dapr/issues/2889

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation

### CODE REVIEW

**Comment by berndverst** [comment]
Codecov is wrong. Nothing changed here that would eliminate the use of `sdk/src/main/java/io/dapr/utils/Retry.java` or lower test coverage.

**Comment by berndverst** [comment]
Sorry about the unnecessary reformatting of some code. VSCode did that.

**Review by artursouza — APPROVED** [review]

**Comment by artursouza** [comment]
Let's wait until the runtime PR is merged before merging this. Thanks, @berndverst

**Comment by berndverst** [comment]
@artursouza runtime is merged. Do you want to merge this now?

**Pull request merged**
