### PR TITLE
Bump supported Spring Boot baseline to version 3.2.x

### PR DESCRIPTION
**Pull request by ThomasVitale**
# Description

Spring Boot < 3.2.x reached end of life and it's not maintained anymore. This PR bumps the minimum supported version to 3.2.x, supporting both the 3.2.x and 3.3.x release trains.

* Bump dependencies in sdk-springboot module from Spring Boot 2.x to 3.2.6
* Update examples module to use new Spring Boot support with Java 17 baseline
* Fix wrong sdkman and maven wrapper setup that failed the local setup
* Update GHA workflow to stop testing for Spring Boot versions < 3.2.x

## Issue reference

Fixes gh-1039

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [x] Extended the documentation

### CODE REVIEW

**Comment by salaboy** [comment]
@artursouza I just checked this PR.. and this is what we need to do to upgrade to spring 3.2.x .. We will start refactoring the spring boot support, trying not to break existing users.

**Comment by salaboy** [comment]
@artursouza can you please review?

**Comment by cicoyle** [comment]
Looks like CI is failing the `license/synk` check, but I can't view it. I'm fine with proceeding with this change given if there are vulnerabilities in Spring Boot < 3.2.x it won't be fixed and users have had some time to upgrade by now.

**Comment by ThomasVitale** [comment]
@cicoyle thanks for the review. I can't see the Snyk report either. @salaboy do you have access? I'm not sure which  dependency is triggering the failure.

**Comment by salaboy** [comment]
@cicoyle when you have time can you please validate this one? now that the HTTP client is removed .. we need to upgrade the spring boot version.

**Comment by salaboy** [comment]
> @cicoyle thanks for the review. I can't see the Snyk report either. @salaboy do you have access? I'm not sure which dependency is triggering the failure.

Let me ask for permission

**Comment by salaboy** [comment]
Screenshot 2024-06-26 at 15 35 52

**Comment by salaboy** [comment]
@ThomasVitale I am working out on the licence stuff.. but it seems that `dapr-sdk-tests` is still trying to get `Could not find artifact io.dapr:dapr-sdk-springboot3:jar:1.12.0-SNAPSHOT ` which might be because you forgot to update that dependency.

**Comment by artursouza** [comment]
> @ThomasVitale I am working out on the licence stuff.. but it seems that `dapr-sdk-tests` is still trying to get `Could not find artifact io.dapr:dapr-sdk-springboot3:jar:1.12.0-SNAPSHOT ` which might be because you forgot to update that dependency. Here: https://github.com/dapr/java-sdk/blob/master/sdk-tests/pom.xml#L132

I fixed it in FOSSA. Ignore Snyk's report on license, I disabled that going forward. Snyk is used for vulnerability reports only.

**Comment by ThomasVitale** [comment]
@salaboy thanks, I had missed that idk-tests was excluded from the multi-module Maven project, so the tests didn't actually run as part of the local workflow. I tried to set them up locally based on the pipeline, but I didn't manage to do it fully, I'm afraid. I pushed a change to update the dependencies in dk-tests, and remove sdk-springboot3.

**Comment by artursouza** [comment]
> @salaboy thanks, I had missed that sdk-tests was excluded from the multi-module Maven project, so the tests didn't actually run as part of the local workflow. I tried to set them up locally based on the pipeline content, but I didn't manage to do it fully, I'm afraid. I pushed a change to update the dependencies in dk-tests, and remove sdk-springboot3. Can you re-run the PR pipeline?

This is a breaking change but it might make sense for the Java community to simply move away from Springboot 2.

**Comment by salaboy** [comment]
Yes we made the decision to move forward to spring 3.2.x .. let’s unblock
this if the PR is green

 - Blog: http://salaboy.com <http://salaboy.wordpress.com>
 - Github user: http://github.com/salaboy
 - Twitter: http://twitter.com/salaboy

 - Mauricio "Salaboy" Salatino -

**Comment by artur-ciocanu** [comment]
@salaboy and @ThomasVitale I have spent some time looking at the build failures. According to this document: https://github.com/spring-projects/spring-framework/wiki/Upgrading-to-Spring-Framework-6.x#parameter-name-retention things have changed in Spring Framework 6.x when it comes to parameter name resolution. We have to either use Java Compiler with `-parameters` flag or ensure that `@PathVariable` and `@RequestPathParam` are explicitly named.

I have run an experiment using explicit naming that can be found here: https://github.com/artur-ciocanu/java-sdk/actions/runs/9696067245/job/26757186160. The GitHub Action succeeded, so we can at least try to fix these issues in the near term.

I am still looking into other build failures. I'll keep you posted.

CC: @artursouza @cicoyle

**Comment by artur-ciocanu** [comment]
@salaboy and @ThomasVitale I have spent a few hours figuring out why the tests are failing. Here are my findings:
- "parameter name resolution" - the are changes in SB 2.x and SB 3.x it is due to Spring Framework 6.x changes. The fixes are trivial I have suggested them in the previous comment.
- OpenTelemetry version mismatch - it seems that as part of SB 3.x upgrade we get a new version of Zipkin reporter and this conflicts with OTEL version that is currently used in `sdk-tests`. Here is the error that I managed to reproduce:
```
Error:  Errors: 
Error:    TracingIT.testInvoke:60 » NoSuchMethod 'zipkin2.Call zipkin2.reporter.Sender.sendSpans(java.util.List)'
Error:    TracingIT.testInvoke:58 » NoSuchMethod 'zipkin2.Call zipkin2.reporter.Sender.sendSpans(java.util.List)'
```

My suggestion for the second issue would be to upgrade OTEL to latest library, but this requires some significant changes in `sdk-tests` since currently it uses `0.14.0` while the latest is `1.39.0`.

@artursouza and @cicoyle what are your thoughts.

**Comment by salaboy** [comment]
@artur-ciocanu I wonder if we can rely on the OTEL stuff that comes with Spring Boot 3.x instead of adding our own dependency

**Comment by artur-ciocanu** [comment]
@cicoyle @artursouza or @ThomasVitale could you please try to merge the "master" and see if we still have any issues with Spring Boot upgrade.

**Comment by ThomasVitale** [comment]
@artur-ciocanu thanks, I'll try that later today

**Comment by ThomasVitale** [comment]
@artur-ciocanu I have rebased this PR and pushed the changes

**Comment by artur-ciocanu** [comment]
@artursouza and @cicoyle it seems that we need maintainers approval. The build workflows are blocked right now.

Whenever you have a chance, could you please help? Thank you.

**Comment by artur-ciocanu** [comment]
@ThomasVitale we are almost there 😀. It seems that there is still one IT test that is failing. It is related to SDK resiliency. I will take a look on Monday and see if I can reproduce it and come up with a fix.

**Comment by salaboy** [comment]
Thanks so much for the help @artur-ciocanu 💪💪

**Comment by artur-ciocanu** [comment]
@ThomasVitale and @salaboy I have opened #1070 to try to fix the SDK resiliency IT failure. Let's wait until it is merged and see if it will fix the issue.

**Comment by artur-ciocanu** [comment]
@ThomasVitale the SDK resiliency IT fix PR has been merged. Could you please merge "master" and see if things are looking good.

**Comment by ThomasVitale** [comment]
@artur-ciocanu thanks! I've just rebased the PR

**Comment by artur-ciocanu** [comment]
@artursouza or @cicoyle it seems that we need maintainers approval to kick off the GitHub workflows. Could you please approve and if everything looks merge the PR.

Thank you! 🙇‍♀️

**Comment by yaron2** [comment]
Need to check why the build is failing

**Comment by artursouza** [comment]
Build is still failing. I have no problem merging this once validation passes.

**Comment by artur-ciocanu** [comment]
Let me check tomorrow one more time to see what might be the issue. Thanks for checking @artursouza 🙇

**Comment by ThomasVitale** [comment]
Thanks! I would like to help debug the integration tests, but I didn't manage to run them locally. I have suggested an improvement for the docs on how to establish a local setup for running the sdk-tests project. https://github.com/dapr/java-sdk/issues/1075

**Comment by artur-ciocanu** [comment]
@artursouza and @yaron2 I have opened a tiny PR #1077 to add failure message for the failed IT test. Also I have tried to build #1050 from my fork and the GitHub workflow completed successfully. Here are is the build run: https://github.com/artur-ciocanu/java-sdk/actions/runs/9904795676.

If you could review PR #1077 and merge it to `master` then we could at least see what is the underlying problem.

Thank you!

**Comment by artur-ciocanu** [comment]
@artursouza sorry for this back and forth, but you could you please merge master and retrigger the GitHub workflows.

Much appreciated.

**Comment by artur-ciocanu** [comment]
@artursouza sorry for this back and forth, but could you please merge master and retrigger the GitHub workflows.

Thank you, much appreciated. 🙇‍♂️

**Comment by artur-ciocanu** [comment]
@artursouza as far as I can see the Spring Boot 3.x build was successful. The other Spring Boot builds like 2.5, 2.6, 2.7, 3.0 are stuck. However these have been removed from the test matrix in the GitHub workflow. Also if I go to https://github.com/dapr/java-sdk/pull/1050/checks everything seems to be 🟢 .

Do you think it is safe to merge this PR that the SB 3.2 and SB 3.3 builds are successful?

**Comment by artur-ciocanu** [comment]
@artursouza and @cicoyle whenever you have a few minutes could you please take a final look, approve and merge. Thank you.

**Comment by salaboy** [comment]
@cicoyle can you please review this?

**Comment by artursouza** [comment]
OK. This is going to release 1.12.

**Review by artursouza — APPROVED** [review]

**Comment by artur-ciocanu** [comment]
@artursouza it seems to be 🟢 !!!

**Comment by marcduiker** [comment]
@holopin-bot @ThomasVitale Thank you Thomas!

**Pull request merged**
