### PR TITLE
Update project-reactor dependency & fix deprecated calls

### PR DESCRIPTION
**Pull request by Gonzoe79**
updating project reactor dependency to work with spring boot 3, replacing deprecated calls to subscriberContext

Signed-off-by: Jan Czapla <jan.czapla@bosch.com>

# Description

_Please explain the changes you've made_

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation

### CODE REVIEW

**Comment by mukundansundar** [comment]
@Gonzoe79 can you fix the checkstyle violations?

**Comment by artursouza** [comment]
Although this is a breaking change due to the dependency change, I can accept this PR if the integration tests pass. Please, take a look that they are all failing consistently.

**Comment by cicoyle** [comment]
gentle ping - @Gonzoe79

**Comment by artursouza** [comment]
We already upgraded to Springboot 3. Closing PR. Thanks.

**Pull request closed without merging**
