### PR TITLE
Drop Java 8 API compatibility, enforce Java 11 API compatibility

### PR DESCRIPTION
**Pull request by artur-ciocanu**
# Description

This removes Maven Animal Sniffer plugins and ensures that Dapr Java SDK enforces Java 11 API compatibility. This eventually will help us migrate to Java 17, when we are ready.

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #1092

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation

### CODE REVIEW

**Comment by artur-ciocanu** [comment]
@artursouza and @cicoyle do let me know if you think this PR can be merged or if there are valid reason to force Java 8 API compatibility.

**Comment by artur-ciocanu** [comment]
@artursouza and @cicoyle could you please review and let me know if this PR looks good. Thank you!

**Comment by artur-ciocanu** [comment]
@artursouza as discussed over Discord, could you please approve this PR? Thank you.

**Comment by artur-ciocanu** [comment]
@artursouza and @cicoyle could you please review, approve and merge. Thank you!

**Review by cicoyle — APPROVED** [review]
This looks ok to me given people who want java 8 still will use earlier versions of the sdk.

**Review by artursouza — APPROVED** [review]

**Pull request merged**
