### PR TITLE
#815 Upgrade and fix issues for new Reactor version.

### PR DESCRIPTION
**Pull request by MatejNedic**
# Description

Solves #815 

## Issue reference
#815 

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [x] Extended the documentation

### CODE REVIEW

**Comment by MatejNedic** [comment]
Will upgrade to spring boot 3.0.2 and see how it will go.

**Comment by champel** [comment]
I created #830, that allows to use reactor only upgrading this dependency. In order to get closer to Spring Boot 3, i also propose #831 in order to upgrade to the latest version 2 of Spring boot. Both PR are passing integration tests and validation in my account. @MatejNedic and me are working in a project where we have migrated to Spring Boot 3 but we want still to use the awesome dapr.

**Comment by MatejNedic** [comment]
@champel from what I have seen it will require changing some code since with Java 17 I had build issues.

**Comment by champels** [comment]
@MatejNedic , the pipeline is building with versions 11,13,15 and 16. So I downgraded my local version to 11 to build the sdk.

**Comment by MatejNedic** [comment]
Closing in favour of #830

**Pull request closed without merging**
