### PR TITLE
Use state serializer content type when saving actor states.

### PR DESCRIPTION
**Pull request by antoniomaria**
# Description

Use state serializer content type when saving dapr states. 

## Issue reference

Please reference the issue this PR will close:  https://github.com/dapr/java-sdk/issues/1031

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [ ] Extended the documentation

### CODE REVIEW

**Review by artursouza — APPROVED** [review]

**Comment by artursouza** [comment]
I am want to take this PR, although it is a breaking change.

**Comment by antoniomaria** [comment]
Be my guest. Thanks for take it.

**Comment by antoniomaria** [comment]
Did I understand correctly that @artursouza will take this PR to the goal?
Or Can I still do something? like fixing Integration tests, or documentation?

**Comment by mukundansundar** [comment]
@artursouza Qq if state serializer is used when serializing, shouldn't there be an option during desirialization as well? 
Also do you think serializer option could be part of StateOptions? `useCustomSerializer` or `useStateSerializer`, and that could be used during both Save and Get State also?

**Comment by artursouza** [comment]
> @artursouza Qq if state serializer is used when serializing, shouldn't there be an option during desirialization as well? Also do you think serializer option could be part of StateOptions? `useCustomSerializer` or `useStateSerializer`, and that could be used during both Save and Get State also?

Can you elaborate because this PR is just about setting the content type.

**Comment by artursouza** [comment]
> Did I understand correctly that @artursouza will take this PR to the goal? Or Can I still do something? like fixing Integration tests, or documentation?

Sorry for the ambiguity. By taking this PR, I meant accepting it. But the validation is failing.

**Comment by antoniomaria** [comment]
> > Did I understand correctly that @artursouza will take this PR to the goal? Or Can I still do something? like fixing Integration tests, or documentation?
> 
> Sorry for the ambiguity. By taking this PR, I meant accepting it. But the validation is failing.

Ah sorry, I missed your answer. Perhaps some NPE exception somewhere, I can have a look

**Comment by antoniomaria** [comment]
Dapr side car doesn't seem to like the content type if the state is null. I checked for it. Please review @artursouza

**Comment by antoniomaria** [comment]
@mukundansundar did you have time to review this MR?

**Review by cicoyle — APPROVED** [review]

**Comment by antoniomaria** [comment]
I don't see the button "Merge PR", is it because the branch is out of date? or because I don't have access to merge a PR ?

**Comment by cicoyle** [comment]
Only maintainers have the ability to merge - cc: @artursouza plz take another pass

**Comment by marcduiker** [comment]
@holopin-bot @antoniomaria Thank you!

**Pull request merged**
