### PR TITLE
Enable dependabot for all packages.

### PR DESCRIPTION
**Pull request by berndverst**
# Description

Replaces stale PR #499 to enable Dependabot.

### CODE REVIEW

**Comment by berndverst** [comment]
Please take a look: @mukundansundar @halspang @artursouza

**Review by halspang — APPROVED** [review]
Looks good to me. I'm curious to see how often things will actually update after the first set.

**Comment by berndverst** [comment]
@halspang apparently I need to pause this PR at the moment to update this for the requirements in #348:

@mukundansundar @artursouza 

It seems we want:
- Dependabot making PRs into the `dependabot` branch (to be created)
- Tests to run in the `dependabot` branch and upon success to create a PR against the master branch.

The problem I see here is... 
Doesn't this mean the `dependabot` branch needs to be synced against master regularly?

**Comment by halspang** [comment]
> The problem I see here is...
> Doesn't this mean the dependabot branch needs to be synced against master regularly?

Yes, but that could also be part of a workflow. Just merge master into it at some regular cadence. Or even as part of the workflow it could create, PR, merge, and then delete its own branch so it's fresh every time. That's what I'd go for personally but I think that relies on us being able to trigger dependabot instead of it going on its own cadence.

**Review by artursouza — APPROVED** [review]

**Comment by berndverst** [comment]
Given that this PR was merged we will need to be careful not to approve every PR dependabot creates. This PR was never updated to use the special branch concept. However, doing so would also be unnecessarily complex and also error prone.

**Pull request merged**
