### PR TITLE
Add FOSSA workflow and badge

### PR DESCRIPTION
**Pull request by shubham1172**
Signed-off-by: Shubham Sharma <shubhash@microsoft.com>

# Description

Adds the FOSSA workflow and badge.
Also fixes the license badge from MIT to Apache 2.0

## Issue reference

Please reference the issue this PR will close: #695

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* (NA) Code compiles correctly
* (NA) Created/updated tests
* (NA) Extended the documentation

### CODE REVIEW

**Comment by shubham1172** [comment]
Resolving this false-positive.
image
Source code: https://github.com/google/guava

**Review by mukundansundar — APPROVED** [review]
lgtm

**Comment by mukundansundar** [comment]
> Resolving this as false-positive.
> image
> Source code: https://github.com/google/guava

This is a dependency for the Google protobuf java library used by this project.

**Review by tanvigour — APPROVED** [review]
LGTM

**Pull request merged**
