### PR TITLE
Fix doc references to preview for configuration API.

### PR DESCRIPTION
**Pull request by artursouza**
# Description

Fix doc references to preview for configuration API.

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: N/A

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation

### CODE REVIEW

**Comment by artursouza** [comment]
cc @mukundansundar

**Review by msfussell — DISMISSED** [review]
Lgtm

**Review by skyao — APPROVED** [review]
LGTM

**Review by cicoyle — APPROVED** [review]
LGTM

**Comment by cicoyle** [comment]
@mukundansundar - mind merging this?

**Pull request merged**
