### PR TITLE
Replace deprecated cli options with new ones

### PR DESCRIPTION
**Pull request by pruthvidhodda**
# Description

Replaced deprecated cli options with new ones

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #317 

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation

### CODE REVIEW

**Comment by artursouza** [comment]
It depends on the change. For starters, update DAPR_CLI_REF in the github actions file to point to the latest cli commit id.

**Comment by pruthvidhodda** [comment]
> It depends on the change. For starters, update DAPR_CLI_REF in the github actions file to point to the latest cli commit id.

So can I update this in the master and revert it after the build passes?

**Comment by artursouza** [comment]
Just make the change here in the same PR. It will run the validation using the latest Dapr runtime.

**Comment by pruthvidhodda** [comment]
Reverted workflow changes as discussed above. Merging it as it's already approved.

**Comment by artursouza** [comment]
@pruthvidhodda  This change broke the build.

**Comment by pruthvidhodda** [comment]
> @pruthvidhodda This change broke the build.

It's because I reverted CLI_REF. @mukundansundar added it back in his PR, will take a look if that doesn't work.

**Pull request merged**
