### PR TITLE
[WIP] Add support for TTL and time/interval formats in actor timers/reminders #652

### PR DESCRIPTION
**Pull request by Giovds**
# Description

This PR should add the following items:

**ActorTimers**
- [x] Add TTL option
- [x] Allow for repetitions in TTL and Period with ISO-8601 format

**ActorReminders**
- [x] Add TTL option
- [x] Allow for repetitions in TTL and Period with ISO-8601 format

**Integration test**
- [ ] Add integration test validating the added features

## Issue reference

The issue this PR will close: #652

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation

### CODE REVIEW

**Comment by mukundansundar** [comment]
@Giovds Is there any progress in this?

**Comment by Giovds** [comment]
@mukundansundar I haven't had the time to finish this yet, and I will still be unavailable next week. I expect to have time again afterwards. I think what is left is to write integration tests to prove that it works, but I couldn't get them to run them locally yet.

**Comment by mukundansundar** [comment]
@Giovds nudge - is there any update on this PR ?

**Comment by Giovds** [comment]
> @Giovds nudge - is there any update on this PR ?

https://github.com/dapr/java-sdk/issues/652#issuecomment-1039494012

**Comment by cicoyle** [comment]
gentle ping - @Giovds. Please see README as to how to run the tests locally

**Comment by Giovds** [comment]
I unfortunately don’t plan on working on this topic anymore. Feel free to use this branch as inspiration.

**Pull request closed without merging**
