### PR TITLE
enable Dependabot v2

### PR DESCRIPTION
**Pull request by sullis**
# Description

https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation

### CODE REVIEW

**Comment by mukundansundar** [comment]
Hi @sullis this is related to this issue #348 

Please also see the comment ... https://github.com/dapr/java-sdk/issues/348#issuecomment-706664126

**Comment by artursouza** [comment]
@mukundansundar @sullis Can dependabot update all pom files at once?

**Comment by mukundansundar** [comment]
> @mukundansundar @sullis Can dependabot update all pom files at once?
@artursouza 
Please see comment https://github.com/dapr/java-sdk/issues/348#issuecomment-706664126

**Comment by berndverst** [comment]
Answering @artursouza's comment -- yes we can update all pom files. Let me make a new PR to get this done.

**Comment by artursouza** [comment]
Closing in favor of #570

**Pull request closed without merging**
