### PR TITLE
Adding Java header to parent pom.xml

### PR DESCRIPTION
**Pull request by artur-ciocanu**
# Description

This PR fixes a tiny issue with Checkstyle so we can run it from submodules as well. This was discovered by @salaboy.

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #1086

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation

### CODE REVIEW

**Comment by artur-ciocanu** [comment]
@artursouza and @cicoyle this is another tiny PR that requires your attention. Thank you!

**Comment by artur-ciocanu** [comment]
@artursouza and @cicoyle I was wondering is there a way to re-trigger the build? Sometimes we have IT tests failing because of container setup delays etc and I think it would be good to have a way to re-trigger the build without commits.

**Comment by artursouza** [comment]
I do rerun them on GH actions. But GH only allows that with certain permissions, it is not open to all.

**Comment by artur-ciocanu** [comment]
> I do rerun them on GH actions. But GH only allows that with certain permissions, it is not open to all. 

I see, makes sense. @artursouza if the PR looks good could you please merge?

**Review by artursouza — APPROVED** [review]

**Pull request merged**
