### PR TITLE
allow supplied ObjectMapper to DefaultObjectSerializer

### PR DESCRIPTION
**Pull request by xiazuojie**
# Description

allow supplied ObjectMapper to DefaultObjectSerializer so that JSON serialization behaviour can be customised

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #496 

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [x] Extended the documentation

### CODE REVIEW

**Review by mukundansundar — APPROVED** [review]
lgtm

**Review by artursouza — CHANGES_REQUESTED** [review]
Application's should provide their own serializer for their objects. The internal serialization for Actor objects is not configurable and is implemented in a way that allows cross language SDKs examples.

**Comment by artursouza** [comment]
Another reason not to merge this PR is that ObjectMapper from Jackson package would become part of our contract. That should remain transparent to applications.

Again, apps are expected to provide their own serializer and not use DefaultObjectSerializer beyond samples and getting started.

**Comment by artursouza** [comment]
@xiazuojie Thanks for continuing to make proposals here in the Dapr's Java SDK. Please, consider joining us in our Discord server: https://discord.com/channels/778680217417809931/778749797242765342

**Pull request closed without merging**
