### PR TITLE
Update Dapr runtime and CLI.

### PR DESCRIPTION
**Pull request by artursouza**
# Description

Update to the latest released CLI and runtime - doing it in steps to make sure we detect the exact change if there are issues.

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: N/A

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation

### CODE REVIEW

**Comment by artursouza** [comment]
Don't merge yet. This is running for 1.11.0 first.

**Comment by artursouza** [comment]
For 1.11.0, all ITs passed but there is flakiness with SdkResiliencyIT: https://github.com/dapr/java-sdk/actions/runs/6090432602

Next, 1.11.1

**Comment by artursouza** [comment]
1.11.1 -> all ITs passed: https://github.com/dapr/java-sdk/actions/runs/6091205370

**Comment by artursouza** [comment]
1.11.2 -> All ITs passes (ActorTuenBasedConcurrencyIT had one run that failed): https://github.com/dapr/java-sdk/actions/runs/6092868491/job/16531668966

**Comment by artursouza** [comment]
All ITs passed with 1.11.3 too. One flaky run for ActivationDeactivationIT. https://github.com/dapr/java-sdk/actions/runs/6093159879/job/16532365408?pr=899

**Review by skyao — APPROVED** [review]
LGTM

**Review by mukundansundar — APPROVED** [review]

**Pull request merged**
