### PR TITLE
Test SDK release branch with latest RC version of runtime and CLI

### PR DESCRIPTION
**Pull request by mukundansundar**
# Description

Test release branch with latest RC of runtime and CLI.
Contains previous cherry picked commit from master and change to RC 4 for runtime.

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: endgame

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation

### CODE REVIEW

**Comment by mukundansundar** [comment]
only verification of Actors is pending.

**Comment by mukundansundar** [comment]
Running Actor Example ... The following is the output from 

DemoActorService 
```
INFO[0015] placement tables updated, version: 1          app_id=demoactorservice instance=local scope=dapr.runtime.actor.internal.placement type=log ver=1.8.0-rc.4
== APP == 2022-06-28 15:54:25,435 {HH:mm:ss.SSS} [http-nio-3000-exec-8] INFO  io.dapr.actors.ActorTrace - Actor:691a095f-bb2c-4d90-aed1-149f693ee86e Activating ...
== APP == 2022-06-28 15:54:25,437 {HH:mm:ss.SSS} [http-nio-3000-exec-9] INFO  io.dapr.actors.ActorTrace - Actor:b796f603-c4c8-47fa-9ccb-c5c637c820b8 Activating ...
== APP == 2022-06-28 15:54:25,437 {HH:mm:ss.SSS} [http-nio-3000-exec-7] INFO  io.dapr.actors.ActorTrace - Actor:943be708-1e97-43ac-8448-6a6121aa7b4e Activating ...
== APP == 2022-06-28 15:54:25,437 {HH:mm:ss.SSS} [http-nio-3000-exec-9] INFO  io.dapr.actors.ActorTrace - Actor:b796f603-c4c8-47fa-9ccb-c5c637c820b8 Activated
== APP == 2022-06-28 15:54:25,437 {HH:mm:ss.SSS} [http-nio-3000-exec-8] INFO  io.dapr.actors.ActorTrace - Actor:691a095f-bb2c-4d90-aed1-149f693ee86e Activated
== APP == 2022-06-28 15:54:25,437 {HH:mm:ss.SSS} [http-nio-3000-exec-7] INFO  io.dapr.actors.ActorTrace - Actor:943be708-1e97-43ac-8448-6a6121aa7b4e Activated
== APP == Server say method for actor 691a095f-bb2c-4d90-aed1-149f693ee86e: Actor 691a095f-bb2c-4d90-aed1-149f693ee86e said message #1 @ 2022-06-28 15:54:25.964
== APP == Server say method for actor 943be708-1e97-43ac-8448-6a6121aa7b4e: Actor 943be708-1e97-43ac-8448-6a6121aa7b4e said message #1 @ 2022-06-28 15:54:25.964
== APP == Server say method for actor b796f603-c4c8-47fa-9ccb-c5c637c820b8: Actor b796f603-c4c8-47fa-9ccb-c5c637c820b8 said message #1 @ 2022-06-28 15:54:25.964
== APP == Server say method for actor 691a095f-bb2c-4d90-aed1-149f693ee86e: Actor 691a095f-bb2c-4d90-aed1-149f693ee86e said message #2 @ 2022-06-28 15:54:26.677
== APP == Server say method for actor 943be708-1e97-43ac-8448-6a6121aa7b4e: Actor 943be708-1e97-43ac-8448-6a6121aa7b4e said message #2 @ 2022-06-28 15:54:26.718
== APP == Server say method for actor b796f603-c4c8-47fa-9ccb-c5c637c820b8: Actor b796f603-c4c8-47fa-9ccb-c5c637c820b8 said message #2 @ 2022-06-28 15:54:26.739
== APP == Server say method for actor b796f603-c4c8-47fa-9ccb-c5c637c820b8: Actor b796f603-c4c8-47fa-9ccb-c5c637c820b8 said message #3 @ 2022-06-28 15:54:26.933
== APP == Server say method for actor 943be708-1e97-43ac-8448-6a6121aa7b4e: Actor 943be708-1e97-43ac-8448-6a6121aa7b4e said message #3 @ 2022-06-28 15:54:27.175
== APP == Server say method for actor 691a095f-bb2c-4d90-aed1-149f693ee86e: Actor 691a095f-bb2c-4d90-aed1-149f693ee86e said message #3 @ 2022-06-28 15:54:27.308
== APP == Server timer for actor 943be708-1e97-43ac-8448-6a6121aa7b4e: ping! @ 2022-06-28 15:54:27.417
== APP == Server timer for actor b796f603-c4c8-47fa-9ccb-c5c637c820b8: ping! @ 2022-06-28 15:54:27.417
== APP == Server timer for actor 691a095f-bb2c-4d90-aed1-149f693ee86e: ping! @ 2022-06-28 15:54:27.417
== APP == Server say method for actor b796f603-c4c8-47fa-9ccb-c5c637c820b8: Actor b796f603-c4c8-47fa-9ccb-c5c637c820b8 said message #4 @ 2022-06-28 15:54:27.458
```


DemoActorClient 
```
INFO[0000] placement tables updated, version: 1          app_id=demoactorclient instance=local scope=dapr.runtime.actor.internal.placement type=log ver=1.8.0-rc.4
ℹ️  Checking if Dapr sidecar is listening on GRPC port 60132
ℹ️  Dapr sidecar is up and running.
ℹ️  Updating metadata for app command: java -jar target/dapr-java-sdk-examples-exec.jar io.dapr.examples.actors.DemoActorClient
✅  You're up and running! Both Dapr and your app logs will appear here.

== APP == Actor 943be708-1e97-43ac-8448-6a6121aa7b4e got a reply: 2022-06-28 15:54:25.964
== APP == Actor b796f603-c4c8-47fa-9ccb-c5c637c820b8 got a reply: 2022-06-28 15:54:25.964
== APP == Actor 691a095f-bb2c-4d90-aed1-149f693ee86e got a reply: 2022-06-28 15:54:25.964
== APP == Actor 691a095f-bb2c-4d90-aed1-149f693ee86e got a reply: 2022-06-28 15:54:26.677
== APP == Actor 943be708-1e97-43ac-8448-6a6121aa7b4e got a reply: 2022-06-28 15:54:26.718
== APP == Actor b796f603-c4c8-47fa-9ccb-c5c637c820b8 got a reply: 2022-06-28 15:54:26.739
== APP == Actor b796f603-c4c8-47fa-9ccb-c5c637c820b8 got a reply: 2022-06-28 15:54:26.933
== APP == Actor 943be708-1e97-43ac-8448-6a6121aa7b4e got a reply: 2022-06-28 15:54:27.175
```

Output consistent with expected output.

**Review by skyao — APPROVED** [review]
LGTM

**Comment by mukundansundar** [comment]
closing because of #757

**Pull request closed without merging**
