### PR TITLE
IT for failover actor reminder.

### PR DESCRIPTION
**Pull request by artursouza**
# Description

IT for failover actor reminder.

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Relates to: https://github.com/dapr/dapr/issues/2554

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [X] Created/updated tests
* [ ] Extended the documentation

### CODE REVIEW

**Comment by mukundansundar** [comment]
the reminder fire IT added recently seems to be flaky. A rerun of build passed the test https://github.com/dapr/java-sdk/pull/407/checks?check_run_id=1534796822 when before it was failing.

**Comment by artursouza** [comment]
I can look at it again when it fails.

**Review by mukundansundar — APPROVED** [review]
Looks good. But one question. 
@artursouza Is there a scenario where the logs we parse contain only 2 exit logs and the minimum is 1 call so we say the reminder fired because of 2 exit logs with no entry log ... do we need to parse filter and count the Entry and Exit logs separately?

**Comment by artursouza** [comment]
> Looks good. But one question.
> @artursouza Is there a scenario where the logs we parse contain only 2 exit logs and the minimum is 1 call so we say the reminder fired because of 2 exit logs with no entry log ... do we need to parse filter and count the Entry and Exit logs separately?

It is unlikely the exit log to be fired without the entry log. We can change the count logic to check for in enter with a matching exit only. This is very unlikely to happen though.

**Pull request merged**
