### PR TITLE
Update dapr workflow example to be quickstart

### PR DESCRIPTION
**Pull request by skyao**
# Description

Background and requirement: we need a workflow example of dapr java sdk in 1.12 release. 

see:

- https://github.com/dapr/quickstarts/issues/903
- https://github.com/dapr/docs/issues/3670

And in the workflow PR, there is an workflow example: 

- https://github.com/dapr/java-sdk/pull/880

But this example is focused on the functionality of workflow sdk and it's not suitable for new comer as quickstudy, but it is great to be advanced tutorial for developer to deep into dapr workflow.

So after discussed with @macromania , Nyemade, Radhika, we planed to:

- splitting current example in PR  https://github.com/dapr/java-sdk/pull/880 into two parts: one for quick start, one for advanced tutorial
- the quick start in java sdk should follow the style as .net sdk and pythod sdk, and after study these two examples, I decided to follow .net sdk because it has a good user story of Order Processing and designed five activities in this workflow example.
- the example of quick start should be included in 1.12 release, and the advanced tutorial is not required but nice to have.

This PR is for the quick start part.

And since this PR is based on the code of PR https://github.com/dapr/java-sdk/pull/880 which is not merged yet, so please don't merge this PR before PR 880 is merged.

## Issue reference

https:github.com/dapr/quickstarts/issues/903

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation

### CODE REVIEW

**Comment by skyao** [comment]
Updated this PR because PR https://github.com/dapr/java-sdk/pull/880 is merged, now we can start the review of this PR.


@artursouza  @mukundansundar @macromania

**Comment by cicoyle** [comment]
@skyao - should this be closed or what is the status on this? I see we have a `sdk-workflow` example, was this to be another workflow example in the repo? I know there is a [desire to re-write the workflow example](https://github.com/dapr/java-sdk/issues/944) since it could be better separated and explained - not sure if your existing PR here helps with that?

**Comment by hhunter-ms** [comment]
@artursouza should we close this PR? we already have a Java workflow SDK quickstart and docs in the correct repos

**Comment by salaboy** [comment]
It looks like this can be closed.

**Pull request closed without merging**
