### PR TITLE
Inject autoconfiguration in the Spring Boot 3 style

### PR DESCRIPTION
**Pull request by champel**
Signed-off-by: Sergio <champel@gmail.com>

# Description

- Prepare for spring boot 3 using the new way of loading autoconfigurations
- Include compatibility test for previous versions of spring boot
- Fix PubSubIT flaky test to retry during two seconds
- Optimise build workflow (use batch mode & do not re-execute tests in installation phase)

## Issue reference

This issue is related with: #815 and can go with PR #830 to prepare the SDK to be used with Spring Boot 3.

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [x] Extended the documentation

### CODE REVIEW

**Comment by champel** [comment]
Hello @artursouza , I fixed a minor topic in the PR, could you launch again the tests?

**Comment by champel** [comment]
@artursouza, the main topic of this PR is using the new way of injecting autoconfigurations. I included some extra tests and some small improvements in the workflow, but, If needed, I can make the PR small to cover the main topic only.

**Review by artursouza — APPROVED** [review]
Will merge after tests pass. Thanks for your contribution.

**Comment by artursouza** [comment]
Merging now. I will need to change the required build after this merge.

**Pull request merged**
